### ISSUE TITLE
Error When trying to post a message

### ISSUE THREAD

**Issue by Fruggy** [igdmapps/igdm-pro-release#62]
\\AC:\Users\frugg\AppData\Local\Temp\dcb84f00-faa8-419e-a733-60758f9bf2a0.tmp.node is
not a valid Win32 application.
\\?\C:\Users\frugg\AppData\Local\Temp\dcb84f00-faa8-419e-a733-60758f9bf2a0.tmp.node
Error:
\\AC:\Users\frugg\AppData\Local\Temp\dcb84f00-faa8-419e-a733-60758f9bf2a0.tmp.node is
not a valid Win32 application.
\\AC:\Users\frugg\AppData\Local\Temp\dcb84f00-faa8-419e-a733-60758f9bf2a0.tmp.node
at process.func [as dlopen] (electron/js2c/asar.js:140:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
at Object.func [as .node] (electron/js2c/asar.js:149:18)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module.Joad (internal/modules/cjs/loader.js:881:14)
at Function.Module.Joad (electron/js2c/asar.js:779:28)
at Module.require (internal/modules/cjs/loader.js:1023:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous>
(C:\Users\frugg\AppData\Local\Programs\IGdm-Pro\resources\app.asar\node_modules...:13)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module.Joad (internal/modules/cjs/loader.js:881:14)
at Function.Module.Joad (electron/js2c/asar.js:779:28)
at Module.require (internal/modules/cjs/loader.js:1023:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous>
(C:\Users\frugg\AppData\Local\Programs\IGdm-Pro\resources\app.asar\node_modules...:11)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module.Joad (internal/modules/cjs/loader.js:881:14)
at Function.Module.Joad (electron/js2c/asar.js:779:28)

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
