### ISSUE TITLE
macOS - App Crashs After sending

### ISSUE THREAD

**Issue by digitalraumtcc** [igdmapps/igdm-pro-release#64]
I updated to 2.0.4 but not I am not able to send any Messages: 

Module did not self-register: '/var/folders/tx/6n0963515yv8d_h7pcyvk5p00000gp/T/.com.ifedapoolarewaju.desktop.igdm-pro.LiaIY9'.
Error: Module did not self-register: '/var/folders/tx/6n0963515yv8d_h7pcyvk5p00000gp/T/.com.ifedapoolarewaju.desktop.igdm-pro.LiaIY9'.
at process.func [as dlopen] (electron/js2c/asar.js:140:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
at Object.func [as .node] (electron/js2c/asar.js:149:18)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module._load (internal/modules/cjs/loader.js:881:14)
at Function.Module._load (electron/js2c/asar.js:779:28)
at Module.require (internal/modules/cjs/loader.js:1023:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> (/Applications/IGdm-Pro.app/Contents/Resources/app.asar/node_modules/re2/re2.js:3:13)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module._load (internal/modules/cjs/loader.js:881:14)
at Function.Module._load (electron/js2c/asar.js:779:28)
at Module.require (internal/modules/cjs/loader.js:1023:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> (/Applications/IGdm-Pro.app/Contents/Resources/app.asar/node_modules/url-regex-safe/lib/index.js:9:11)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module._load (internal/modules/cjs/loader.js:881:14)
at Function.Module._load (electron/js2c/asar.js:779:28)

**Comment by spinalgr1990** [comment]
The last working version is IG DM Free 3.0.1 

https://github.com/igdmapps/igdm/releases/download/v3.0.0/IGdm-Setup-3.0.0.exe

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
